### ISSUE TITLE
Release under free software license

### ISSUE THREAD

**Issue by throwaway1037** [Inochi2D/inochi-viewer#1]
Some distros cannot package proprietary programs.

**Comment by LunaTheFoxgirl** [comment]
Inochi2D and accompanying software is released under the permissive BSD 2-clause license while branding assets are not.

Distro maintainers that wish to package the official Inochi2D tools just need to package the barebones versions without branding to comply with free license restrictions.

**Comment by throwaway1037** [comment]
Thank you.
So as to make this clear to people who find themselves in possession of these files, the repo should contain a license file and ideally each source file should contain a license header.

**Comment by LunaTheFoxgirl** [comment]
This repository is more meant as a test, Inochi Creator, Session, etc. do have their respective license files, and do by default build as barebones builds without branding assets to make packagers' lives easier.

**Comment by throwaway1037** [comment]
I understand, but people can't be expected to know this conversation exists in order to know it is free software.
Without clear licensing, people do not know their rights.

Moreover, licensing the repo as I have described carries more legal weight than this conversation.

**Comment by LunaTheFoxgirl** [comment]
Inochi2D is not free software (as in GPL terms), it's permissively licensed software. (BSD 2-clause)
Conforming to the FSF's (flawed) definition of free software is not our goal, and won't ever be.

I will be adding a BSD 2-clause license file to this repo though.

**Comment by throwaway1037** [comment]
BSD-2-clause is a free software license.
The license is what makes the program free, so not including it and clearly marking the program means that people won't know their rights unless they somehow read this conversation, and I don't know if your earlier message in this conversation can be regarded as a legal copyright statement.

**Comment by LunaTheFoxgirl** [comment]
A free license is a viral license like the GPL, BSD 2-clause is a permissive license, which is different.
Though it is compatible with GPL according to the FSF, but we purposely avoid using any GPL based dependencies so that our code may be integrated in to proprietary software when our users need it; eg. for game development.

**Comment by throwaway1037** [comment]
No, a free software license is one which respects the four fundamental freedoms of the user.
It may be copyleft like the GNU GPL or lax and permissive like the BSD-2-clause license.
See https://gnu.org/licenses/license-list.html

Moreover, the term "viral" is a smear term historically used by MS and does not actually describe copyleft.

**Comment by throwaway1037** [comment]
Thank you for including the license!
So as people know their rights even if a file is separated from the repo, it would also be best to include license headers in each sorice file.
A license in the root of the repo does not necessarily apply to all source files automatically.

**Comment by LunaTheFoxgirl** [comment]
You can't build this repository outside of the dub ecosystem so not having the entire repo downloaded makes no sense.

Also having large bulky license text at a top of the file is ugly and makes it more difficult to see actually useful information about the file.

**Comment by throwaway1037** [comment]
Regardless, who knows whether a file might be used in isolation, as a code example for instance.

It would be acceptable to place the license information at the end of the file and a simple SPDX identifier on the first line.

**Comment by LunaTheFoxgirl** [comment]
Also it makes sense why the GPL is called viral, it does kind of infect codebases forcing them to effectively switch their license over to GPL. Hence Inochi2D's codebase avoids GPL/LGPL dependencies as much as possible to stay clear, especially when Inochi2D itself is meant to be integrated not only in open source software, but also be used in proprietary settings (games development as an example, again).

If developers need to use Inochi2D or its tools in a proprietary setting or integrate it in to proprietary systems (eg. the rendering backends of games consoles) then it's something we need to be able to support. Hence the distinction, to me.

I think that's all that's needed to be said about this.

**Comment by throwaway1037** [comment]
No, copyleft licenses factually do not behave like viruses.
Viruses spread by proximity, wheras copyleft licenses spread by someone making the deliberate decision to put it there; a spider plant would be a much more apt comparison.

Also, I recommend this project adopts a strong copyleft license (ideally AGPL-3.0-or-later) so as to prevent it being used to restrict people and infringe upon their fundamental freedoms.
