### ISSUE TITLE
No inochi2d-viewer.exe (puppet) file

### ISSUE THREAD

**Issue by Andremichael3** [Inochi2D/inochi-viewer#2]
Hello! I came across your repository and I did not see any .exe file.

**Comment by jalil-salame** [comment]
There is a zip file of the project in the releases, but seeing it is from 2y ago, it might not be compatible with newer versions (this repo also hasn't gotten any updates in a year so...).

I would look at inochi2d-creator or inochi2d-session instead.

**Comment by LunaTheFoxgirl** [comment]
To create models, check out Inochi Creator https://github.com/Inochi2D/inochi-creator
To use models, check out Inochi Session https://github.com/Inochi2D/inochi-session

This is mostly a development tool, not really meant for anything other than rapid inspection of a model for debugging purposes.
